# Generated by Django 5.0.6 on 2024-06-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Open", models.FloatField()),
                ("VWAP", models.FloatField()),
                ("Volume", models.FloatField()),
                ("Turnover", models.FloatField()),
                ("Trades", models.FloatField()),
                ("Deliverable_Volume", models.FloatField()),
                ("Deliverble", models.FloatField()),
                ("day", models.FloatField()),
                ("month", models.FloatField()),
                ("year", models.FloatField()),
                ("Prev_Close", models.FloatField()),
                ("Close", models.FloatField()),
            ],
        ),
    ]
