# Generated by Django 5.0.6 on 2024-06-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("sid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phno", models.CharField(max_length=10)),
                ("college", models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
