# Generated by Django 5.0.6 on 2024-06-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clg",
            fields=[
                ("cid", models.AutoField(primary_key=True, serialize=False)),
                ("Cname", models.CharField(max_length=200)),
                ("Cadress", models.CharField(max_length=200)),
                ("Cphno", models.CharField(max_length=10)),
            ],
        ),
    ]
