# Generated by Django 5.0.6 on 2024-06-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("eid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("sal", models.CharField(max_length=10)),
            ],
        ),
    ]
